### ISSUE TITLE
Broken glossary link

### ISSUE THREAD

**Issue by CBroz1** [datajoint-company/datajoint-docs#8]
In `src/concepts/mantra.md`, the link to the glossary does not work in either github browser or dockerized site deployment

Suggesting:
`[data pipelines](../glossary#data-pipeline)` -> `[data pipelines](../../glossary#data-pipeline)`

**Comment by kabilar** [comment]
Just updated https://github.com/datajoint-company/datajoint-docs/pull/7.  Will be fixed with merge.
